#!/bin/bash
echo "total 36
drwxr-xr-x 2 root root 179 Mar 13 14:06 .
drwxr-xr-x 6 root root 121 Mar 13 11:04 ..
-rwxr--r-- 1 root root  32 Mar 13 11:14 0-hello_world
-rwxr--r-- 1 root root  28 Mar 13 11:44 1-confused_smiley
-rwxr--r-- 1 root root  28 Mar 13 12:19 2-hellofile
-rwxr--r-- 1 root root  39 Mar 13 12:23 3-twofiles
-rwxr--r-- 1 root root  35 Mar 13 13:24 4-lastlines
-rwxr--r-- 1 root root  35 Mar 13 13:22 5-firstlines
-rwxr--r-- 1 root root  36 Mar 13 13:36 6-third_line
-rwxr--r-- 1 root root  81 Mar 13 14:06 7-file
-rw-r--r-- 1 root root  18 Mar 13 11:24 README.md" > ls_cwd_content
